#!/bin/lua

-- @script pass private account file in input and get service account email in output
--
local cjson = require("cjson")

local str = io.read("*a")

local t = cjson.decode(str)

if type(t.client_email) == "string" then
  print(t.client_email)
else
  error("couldn't get email")
end
